import { StyleSheet } from '@react-pdf/renderer';

/** Dense European A4 CV — brand violet accents, ≤ ~3 pages when content is capped. */
export const pdfStyles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    paddingTop: 22,
    paddingBottom: 22,
    paddingHorizontal: 24,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 10,
    borderBottomWidth: 1.25,
    borderBottomColor: '#0f172a',
    paddingBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerLeft: {
    width: '58%',
    paddingRight: 8,
  },
  headerRight: {
    width: '42%',
    alignItems: 'flex-end',
  },
  name: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#0f172a',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  title: {
    fontSize: 9,
    color: '#3b1f63',
    marginTop: 2,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  subtitle: {
    fontSize: 8,
    color: '#334155',
    marginTop: 1,
  },
  contactLine: {
    fontSize: 8,
    color: '#0f172a',
    textAlign: 'right',
    marginBottom: 1.5,
    lineHeight: 1.25,
  },
  section: {
    marginBottom: 7,
  },
  sectionTitleBox: {
    backgroundColor: '#f1f5f9',
    paddingVertical: 2,
    paddingHorizontal: 5,
    marginBottom: 5,
    borderLeftWidth: 2.5,
    borderLeftColor: '#3b1f63',
  },
  sectionTitle: {
    fontSize: 9.5,
    fontWeight: 'bold',
    color: '#020617',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  leftCol: {
    width: '20%',
    paddingRight: 6,
  },
  rightCol: {
    width: '80%',
  },
  period: {
    fontSize: 8,
    color: '#3b1f63',
    fontWeight: 'bold',
  },
  text: {
    fontSize: 8.5,
    color: '#0f172a',
    lineHeight: 1.28,
  },
  boldText: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#020617',
  },
  titleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    marginBottom: 1,
  },
  companyInline: {
    fontSize: 8,
    color: '#3b1f63',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  company: {
    fontSize: 8,
    color: '#3b1f63',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    marginBottom: 2,
  },
  metaText: {
    fontSize: 8,
    color: '#1e293b',
    marginTop: 1,
    marginBottom: 2,
    lineHeight: 1.25,
  },
  metaInline: {
    fontSize: 8,
    color: '#1e293b',
  },
  projectsMoreNotice: {
    marginTop: 3,
    paddingTop: 3,
    borderTopWidth: 0.5,
    borderTopColor: '#cbd5e1',
  },
  projectsMoreText: {
    fontSize: 7.5,
    color: '#1e293b',
    lineHeight: 1.3,
  },
  projectsMoreLink: {
    fontSize: 7.5,
    color: '#3b1f63',
    textDecoration: 'underline',
  },
  bulletList: {
    marginTop: 1,
  },
  bulletItem: {
    fontSize: 8,
    color: '#0f172a',
    marginBottom: 1,
    lineHeight: 1.25,
    paddingLeft: 2,
  },
  skillGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 1,
  },
  skillPill: {
    fontSize: 7.5,
    backgroundColor: '#f1f5f9',
    color: '#0f172a',
    paddingHorizontal: 4,
    paddingVertical: 1.5,
    marginRight: 3,
    marginBottom: 3,
    borderRadius: 2,
    borderWidth: 0.5,
    borderColor: '#cbd5e1',
  },
  compactLine: {
    fontSize: 8.5,
    color: '#0f172a',
    marginBottom: 2,
    lineHeight: 1.25,
  },
});
